version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "effinglegs-dataservice"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9adga4ix2zz3"
s3_prefix = "effinglegs-dataservice"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
