AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dataservice

  SAM Template for effinglegs.rip

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  PersonalStatsFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: personal_stats/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        ApiRequest:
          Type: Api
          Properties:
            Path: /api/{proxy+}
            Method: get
            RestApiId:
              Ref: StairsAPIGateway

  # Our callback API
  StairsAPIGateway:
    Type: AWS::Serverless::Api
    DependsOn: PersonalStatsFn
    Properties:
      StageName: prod
      DefinitionBody:
        swagger: 2.0
        info:
          version: "1.0"
          title: "A nice title"
        basePath: /prod
        schemes:
        - "https"
        - "http"
        paths:
          /api/{proxy+}:
            get:
              responses: {}
              x-amazon-apigateway-integration:
                uri:
                  # You need to build up the ARN with this pattern - you can't just use a !Ref or !GetAtt AFAIK.
                  Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PersonalStatsFn.Arn}/invocations
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                type: "aws_proxy"


# Outputs:
#   # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#   # Find out more about other implicit resources you can reference within SAM
#   # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#   HelloWorldApi:
#     Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#   PersonalStatsFn:
#     Description: "Hello World Lambda Function ARN"
#     Value: !GetAtt PersonalStatsFn.Arn
#   PersonalStatsFnIamRole:
#     Description: "Implicit IAM Role created for Hello World function"
#     Value: !GetAtt PersonalStatsFnRole.Arn
